### ISSUE TITLE
node16 warning

### ISSUE THREAD

**Issue by greenkiwi** [Codeinwp/gha-pr-check-helper#7]
Hi

GitHub is generates the following warning when this action runs:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: preda-bogdan/gha-pr-check-helper@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

How much of an effort would it be to shift it to node 20?

Cheers
Adam

**Comment by preda-bogdan** [comment]
Hi Adam, it shouldn't be to hard.
I will bump the node version, do some checks to make sure nothing breaks and update the master.

Thank you for mentioning this.

**Comment by preda-bogdan** [comment]
I've bumped the node version to node 20. This should not trigger a warning anymore. 
Please confirm that is working for you as expected and I will close this.
